<a href="https://colab.research.google.com/github/2303A51758/2303A51758-b-11-PDS/blob/main/lab2_aug_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# 1. Create a 2D NumPy array for student marks in 3 subjects (5 students example)
# Each row = student, each column = subject
marks = np.array([
    [85, 78, 92],
    [76, 88, 81],
    [90, 94, 89],
    [65, 70, 72],
    [88, 91, 85]
])

print("Student Marks Array:\n", marks)

# 2. Calculate average, minimum, and maximum marks
average_marks = np.mean(marks, axis=1)
min_marks = np.min(marks, axis=1)
max_marks = np.max(marks, axis=1)

print("\nAverage Marks of Each Student:", average_marks)
print("Minimum Marks of Each Student:", min_marks)
print("Maximum Marks of Each Student:", max_marks)

# 3. Slicing to retrieve marks of specific students (e.g., 2nd and 4th students)
print("\nMarks of 2nd and 4th students:\n", marks[[1, 3]])

# 4. Boolean indexing: Find students who scored above 80 in any subject
above_80 = marks > 80
print


Student Marks Array:
 [[85 78 92]
 [76 88 81]
 [90 94 89]
 [65 70 72]
 [88 91 85]]

Average Marks of Each Student: [85.         81.66666667 91.         69.         88.        ]
Minimum Marks of Each Student: [78 76 89 65 85]
Maximum Marks of Each Student: [92 88 94 72 91]

Marks of 2nd and 4th students:
 [[76 88 81]
 [65 70 72]]


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [ ]:
import pandas as pd

# 1. Create a DataFrame from a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'ID': [101, 102, 103, 104, 105],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'HR'],
    'Salary': [48000, 52000, 60000, 45000, 70000]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# 2. Filter employees with salary > 50,000
high_salary = df[df['Salary'] > 50000]
print("\nEmployees with salary > 50,000:\n", high_salary)

# 3. Sort by salary in descending order
sorted_df = df.sort_values(by='Salary', ascending=False)
print("\nDataFrame sorted by salary (descending):\n", sorted_df)

# 4. Add Bonus column (10% of salary)
df['Bonus'] = df['Salary'] * 0.10
print("\nDataFrame with Bonus column:\n", df)

# 5. Calculate total salary expense including bonuses
total_expense = (df['Salary'] + df['Bonus']).sum()
print("\nTotal salary expense including bonuses: ₹", total_expense)

# 6. Save the updated DataFrame to a CSV file
df.to_csv("employee_salary_analysis.csv", index=False)
print("\nCSV file saved as 'employee_salary_analysis.csv'")


Original DataFrame:
       Name   ID Department  Salary
0    Alice  101         HR   48000
1      Bob  102         IT   52000
2  Charlie  103    Finance   60000
3    David  104         IT   45000
4      Eva  105         HR   70000

Employees with salary > 50,000:
       Name   ID Department  Salary
1      Bob  102         IT   52000
2  Charlie  103    Finance   60000
4      Eva  105         HR   70000

DataFrame sorted by salary (descending):
       Name   ID Department  Salary
4      Eva  105         HR   70000
2  Charlie  103    Finance   60000
1      Bob  102         IT   52000
0    Alice  101         HR   48000
3    David  104         IT   45000

DataFrame with Bonus column:
       Name   ID Department  Salary   Bonus
0    Alice  101         HR   48000  4800.0
1      Bob  102         IT   52000  5200.0
2  Charlie  103    Finance   60000  6000.0
3    David  104         IT   45000  4500.0
4      Eva  105         HR   70000  7000.0

Total salary expense including bonuses: ₹ 302500.0

